# Hierarchical Data, the JSON Data Format, and APIs

In [54]:
import pandas as pd

## Shows Data

First we'll work with the "Girls" shows JSON data from the reading.

In [55]:
# Fetch data from a URL
import requests
response = requests.get("https://dlsun.github.io/pods/data/tvshows.json")

import json
data_shows = response.json()

In [56]:
df_shows = pd.json_normalize(data_shows)
df_shows

,id,url,name,type,language,genres,status,runtime,premiered,officialSite,...,externals.thetvdb,externals.imdb,image.medium,image.original,network,webChannel.id,webChannel.name,webChannel.country.name,webChannel.country.code,webChannel.country.timezone
0,139,http://www.tvmaze.com/shows/139/girls,Girls,Scripted,English,"[Drama, Romance]",Ended,30,2012-04-15,http://www.hbo.com/girls,...,220411,tt1723816,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
1,722,http://www.tvmaze.com/shows/722/the-golden-girls,The Golden Girls,Scripted,English,"[Drama, Comedy]",Ended,30,1985-09-14,None,...,71292,tt0088526,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
2,23542,http://www.tvmaze.com/shows/23542/good-girls,Good Girls,Scripted,English,"[Drama, Comedy, Crime]",Running,60,2018-02-26,https://www.nbc.com/good-girls?nbc=1,...,328577,tt6474378,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
3,6771,http://www.tvmaze.com/shows/6771/the-powerpuff...,The Powerpuff Girls,Animation,English,"[Comedy, Action, Science-Fiction]",Running,15,2016-04-04,https://www.cartoonnetwork.com/video/powerpuff...,...,307473,tt4718304,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
4,42726,http://www.tvmaze.com/shows/42726/florida-girls,Florida Girls,Scripted,English,[Comedy],Running,30,2019-07-10,https://poptv.com/floridagirls,...,363682,tt8548870,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
5,32087,http://www.tvmaze.com/shows/32087/chicken-girls,Chicken Girls,Scripted,English,"[Drama, Children, Music]",Running,16,2017-09-05,https://www.youtube.com/playlist?list=PLVewHiZ...,...,339854,None,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,274.0,Brat,United States,US,America/New_York
6,33320,http://www.tvmaze.com/shows/33320/derry-girls,Derry Girls,Scripted,English,[Comedy],Running,30,2018-01-04,http://www.channel4.com/programmes/derry-girls,...,338903,tt7120662,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
7,1955,http://www.tvmaze.com/shows/1955/the-powerpuff...,The Powerpuff Girls,Animation,English,"[Action, Children, Crime]",Ended,30,1998-11-18,None,...,76200,tt0175058,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
8,1073,http://www.tvmaze.com/shows/1073/bomb-girls,Bomb Girls,Scripted,English,"[Drama, Romance, War]",Ended,60,2012-01-04,None,...,254378,tt1955311,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
9,525,http://www.tvmaze.com/shows/525/gilmore-girls,Gilmore Girls,Scripted,English,"[Drama, Comedy, Romance]",Ended,60,2000-10-05,None,...,76568,tt0238784,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN

1\. Summarize the networks represented by these shows and the number of these shows that aired on each network.

In [57]:
df_shows["network.name"].value_counts()

network.name
NBC                2
Cartoon Network    2
HBO                1
Pop                1
Channel 4          1
Global             1
The CW             1
Name: count, dtype: int64

2\. Find the number of seasons for each show in the data. Do this two ways: one which uses `df_shows`, and another that first flattens `data_shows` to a different data frame.

In [58]:
df_seasons = pd.json_normalize(data_shows,
    record_path="seasons",
    meta=["id","name"],
    meta_prefix="show.")

df_seasons.groupby(["show.id","show.name"]).size().reset_index()

   show.id            show.name  0
0      139                Girls  6
1      525        Gilmore Girls  8
2      722     The Golden Girls  7
3     1073           Bomb Girls  2
4     1955  The Powerpuff Girls  6
5     6771  The Powerpuff Girls  3
6    23542           Good Girls  3
7    32087        Chicken Girls  5
8    33320          Derry Girls  2
9    42726        Florida Girls  1

In [59]:
# Method 1
df_shows["number_of_seasons"] = df_shows["seasons"].str.len()

df_shows[["name", "number_of_seasons"]]

                  name  number_of_seasons
0                Girls                  6
1     The Golden Girls                  7
2           Good Girls                  3
3  The Powerpuff Girls                  3
4        Florida Girls                  1
5        Chicken Girls                  5
6          Derry Girls                  2
7  The Powerpuff Girls                  6
8           Bomb Girls                  2
9        Gilmore Girls                  8

In [60]:
# Method 2
df_seasons = pd.json_normalize(
    data_shows,
    record_path="seasons",
    meta="name",
    meta_prefix="show_"
)

df_seasons.head()

,id,url,number,name,episodeOrder,premiereDate,endDate,webChannel,summary,episodes,...,image.original,image,network,webChannel.id,webChannel.name,webChannel.country,webChannel.country.name,webChannel.country.code,webChannel.country.timezone,show_name
0,650,http://www.tvmaze.com/seasons/650/girls-season-1,1,,10.0,2012-04-15,2012-06-17,NaN,None,"[{'id': 10820, 'url': 'http://www.tvmaze.com/e...",...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Girls
1,651,http://www.tvmaze.com/seasons/651/girls-season-2,2,,10.0,2013-01-13,2013-03-17,NaN,None,"[{'id': 10830, 'url': 'http://www.tvmaze.com/e...",...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Girls
2,652,http://www.tvmaze.com/seasons/652/girls-season-3,3,,12.0,2014-01-12,2014-03-23,NaN,None,"[{'id': 10840, 'url': 'http://www.tvmaze.com/e...",...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Girls
3,653,http://www.tvmaze.com/seasons/653/girls-season-4,4,,10.0,2015-01-11,2015-03-22,NaN,None,"[{'id': 40963, 'url': 'http://www.tvmaze.com/e...",...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Girls
4,21282,http://www.tvmaze.com/seasons/21282/girls-seas...,5,,10.0,2016-02-21,2016-04-17,NaN,,"[{'id': 409239, 'url': 'http://www.tvmaze.com/...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Girls

In [61]:
# Method 2
df_seasons.groupby("show_name")["number"].nunique()

show_name
Bomb Girls             2
Chicken Girls          5
Derry Girls            2
Florida Girls          1
Gilmore Girls          8
Girls                  6
Good Girls             3
The Golden Girls       7
The Powerpuff Girls    6
Name: number, dtype: int64

3\. For each episode, find the length (number of characters) of the title. Then create summaries to answer: Which show tends to have the longest episode titles? The shortest?

In [62]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
df_episodes = pd.json_normalize(data_shows,
    record_path=["seasons", "episodes"],
    meta="name",
    meta_prefix="show_"
)

df_episodes

,id,url,name,season,number,airdate,airtime,airstamp,runtime,summary,image.medium,image.original,image,show_name
0,10820,http://www.tvmaze.com/episodes/10820/girls-1x0...,Pilot,1,1.0,2012-04-15,22:30,2012-04-16T02:30:00+00:00,30,<p>In the premiere of this comedy about twenty...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,Girls
1,10821,http://www.tvmaze.com/episodes/10821/girls-1x0...,Vagina Panic,1,2.0,2012-04-22,22:30,2012-04-23T02:30:00+00:00,30,<p>An appointment at a women's clinic doesn't ...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,Girls
2,10822,http://www.tvmaze.com/episodes/10822/girls-1x0...,All Adventurous Women Do,1,3.0,2012-04-29,22:30,2012-04-30T02:30:00+00:00,30,<p>Hannah contacts her college boyfriend to fi...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,Girls
3,10823,http://www.tvmaze.com/episodes/10823/girls-1x0...,Hannah's Diary,1,4.0,2012-05-06,22:30,2012-05-07T02:30:00+00:00,30,<p>Adam's risqué text message sends Hannah ove...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,Girls
4,10824,http://www.tvmaze.com/episodes/10824/girls-1x0...,Hard Being Easy,1,5.0,2012-05-13,22:30,2012-05-14T02:30:00+00:00,30,<p>Hannah tries a different tack with her boss...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,Girls
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,47635,http://www.tvmaze.com/episodes/47635/gilmore-g...,Hay Bale Maze,7,18.0,2007-04-17,21:00,2007-04-18T01:00:00+00:00,60,<p>Brief encounter: Stars Hollow's centerpiece...,NaN,NaN,NaN,Gilmore Girls
737,47636,http://www.tvmaze.com/episodes/47636/gilmore-g...,It's Just Like Riding a Bike,7,19.0,2007-04-24,21:00,2007-04-25T01:00:00+00:00,60,<p>Lorelai needs help shopping for a new car. ...,NaN,NaN,NaN,Gilmore Girls
738,47637,http://www.tvmaze.com/episodes/47637/gilmore-g...,Lorelai? Lorelai?,7,20.0,2007-05-01,21:00,2007-05-02T01:00:00+00:00,60,"<p>On karaoke night, a tipsy Lorelai take the ...",NaN,NaN,NaN,Gilmore Girls
739,47638,http://www.tvmaze.com/episodes/47638/gilmore-g...,Unto the Breach,7,21.0,2007-05-08,21:00,2007-05-09T01:00:00+00:00,60,<p>Pomp and circumstances. Rory's graduation b...,NaN,NaN,NaN,Gilmore Girls
740,47639,http://www.tvmaze.com/episodes/47639/gilmore-g...,Bon Voyage,7,22.0,2007-05-15,21:00,2007-05-16T01:00:00+00:00,60,<p>An exciting job offer for Rory and a benefi...,NaN,NaN,NaN,Gilmore Girls

In [63]:
df_episodes["title_length"] = df_episodes["name"].str.len()

df_episodes[["show_name", "name", "title_length"]].head()

  show_name                      name  title_length
0     Girls                     Pilot             5
1     Girls              Vagina Panic            12
2     Girls  All Adventurous Women Do            24
3     Girls            Hannah's Diary            14
4     Girls           Hard Being Easy            15

In [64]:
title_summary = (
    df_episodes.groupby("show_name")["title_length"]
    .mean()
    .sort_values(ascending=False)
)

title_summary

show_name
Gilmore Girls          21.431373
The Powerpuff Girls    21.184080
Florida Girls          20.400000
The Golden Girls       19.723757
Chicken Girls          16.434211
Good Girls             15.461538
Bomb Girls             14.421053
Girls                  13.111111
Derry Girls            12.500000
Name: title_length, dtype: float64

4\. Do any cast members in the data set share a birthday with you? Who, and what show are they on? (If there isn't anyone, try a different day.)

In [65]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
df_cast = pd.json_normalize(
    data_shows,
    record_path="cast",
    meta="name",
    meta_prefix="show."
)

df_cast

,self,voice,person.id,person.url,person.name,person.country.name,person.country.code,person.country.timezone,person.birthday,person.deathday,...,person.image.medium,person.image.original,character.id,character.url,character.name,character.image.medium,character.image.original,person.country,character.image,show.name
0,False,False,27410,http://www.tvmaze.com/people/27410/lena-dunham,Lena Dunham,United States,US,America/New_York,1986-05-13,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,36886,http://www.tvmaze.com/characters/36886/girls-h...,Hannah Horvath,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Girls
1,False,False,11102,http://www.tvmaze.com/people/11102/allison-wil...,Allison Williams,United States,US,America/New_York,1988-04-13,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,36887,http://www.tvmaze.com/characters/36887/girls-m...,Marnie Michaels,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Girls
2,False,False,27411,http://www.tvmaze.com/people/27411/jemima-kirke,Jemima Kirke,United Kingdom,GB,Europe/London,1985-04-26,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,36888,http://www.tvmaze.com/characters/36888/girls-j...,Jessa Johansson,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Girls
3,False,False,16405,http://www.tvmaze.com/people/16405/zosia-mamet,Zosia Mamet,United States,US,America/New_York,1988-02-02,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,36889,http://www.tvmaze.com/characters/36889/girls-s...,Shoshanna Shapiro,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Girls
4,False,False,24858,http://www.tvmaze.com/people/24858/adam-driver,Adam Driver,United States,US,America/New_York,1983-11-19,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,36890,http://www.tvmaze.com/characters/36890/girls-a...,Adam Sackler,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Girls
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,False,False,20369,http://www.tvmaze.com/people/20369/edward-herr...,Edward Herrmann,United States,US,America/New_York,1943-07-21,2014-12-31,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,85545,http://www.tvmaze.com/characters/85545/gilmore...,Richard Gilmore,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Gilmore Girls
108,False,False,3354,http://www.tvmaze.com/people/3354/jared-padalecki,Jared Padalecki,United States,US,America/New_York,1982-07-19,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,85552,http://www.tvmaze.com/characters/85552/gilmore...,Dean Forester,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Gilmore Girls
109,False,False,18121,http://www.tvmaze.com/people/18121/matt-czuchry,Matt Czuchry,United States,US,America/New_York,1977-05-20,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,85550,http://www.tvmaze.com/characters/85550/gilmore...,Logan Huntzberger,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Gilmore Girls
110,False,False,20026,http://www.tvmaze.com/people/20026/milo-ventim...,Milo Ventimiglia,United States,US,America/New_York,1977-07-08,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,85553,http://www.tvmaze.com/characters/85553/gilmore...,Jess Mariano,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Gilmore Girls
111,False,False,27417,http://www.tvmaze.com/people/27417/chris-eigeman,Chris Eigeman,United States,US,America/New_York,1965-03-01,None,...,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,85554,http://www.tvmaze.com/characters/85554/gilmore...,Jason Stiles,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,Gilmore Girls

In [66]:
df_cast["person.birthday"] = pd.to_datetime(
    df_cast["person.birthday"],
    errors="coerce"
)

In [67]:
birthday_matches = df_cast[
    (df_cast["person.birthday"].dt.month == 10) &
    (df_cast["person.birthday"].dt.day == 5)
]

In [68]:
birthday_matches[
    ["person.name", "person.birthday", "show.name"]
].drop_duplicates()

Empty DataFrame
Columns: [person.name, person.birthday, show.name]
Index: []

No one shares a birthday with me :(

In [69]:
birthday_matches = df_cast[
    (df_cast["person.birthday"].dt.month == 10) &
    (df_cast["person.birthday"].dt.day == 1)
]

In [70]:
birthday_matches[
    ["person.name", "person.birthday", "show.name"]
].drop_duplicates()

      person.name person.birthday   show.name
19  Izzy Stannard      2004-10-01  Good Girls

## TVMaze API

Now you will work with the [TVMaze API](http://www.tvmaze.com/api) from the reading. Use the API to request JSON data that you can use to answer the following questions.

1\. What was the longest show that aired in the U.S. on February 4, 2018?

_Hint:_ Use the ["Schedule" endpoint](http://www.tvmaze.com/api#schedule) to first get the data for all shows that aired on that date.

In [71]:
# YOUR CODE HERE. ADD CELLS AS NEEDED

response = requests.get("https://api.tvmaze.com/schedule", params={"country":"us", "date":"2018-02-04"})
print(response.status_code)

200

In [72]:
schedule = response.json()

In [73]:
df_schedule = pd.json_normalize(schedule)
df_schedule

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,...,image.medium,image.original,show.network,show.webChannel.id,show.webChannel.name,show.webChannel.country.name,show.webChannel.country.code,show.webChannel.country.timezone,show.webChannel.officialSite,show.image
0,1442787,https://www.tvmaze.com/episodes/1442787/1st-lo...,Going for Gold in PyeongChang,9,14.0,regular,2018-02-03,01:02,2018-02-04T06:02:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1388511,https://www.tvmaze.com/episodes/1388511/americ...,Ultimate Italian,18,5.0,regular,2018-02-03,02:30,2018-02-04T07:30:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1387556,https://www.tvmaze.com/episodes/1387556/marvel...,"Spider-Island, Part One",1,19.0,regular,2018-02-04,07:00,2018-02-04T12:00:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1387558,https://www.tvmaze.com/episodes/1387558/marvel...,"Spider-Island, Part Two",1,20.0,regular,2018-02-04,07:30,2018-02-04T12:30:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1390384,https://www.tvmaze.com/episodes/1390384/ben-10...,High Stress Express,2,11.0,regular,2018-02-04,13:00,2018-02-04T13:00:00+00:00,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1390385,https://www.tvmaze.com/episodes/1390385/ben-10...,Creature Feature,2,12.0,regular,2018-02-04,13:15,2018-02-04T13:15:00+00:00,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1404174,https://www.tvmaze.com/episodes/1404174/meet-t...,"February 4, 2018",2018,5.0,regular,2018-02-04,09:00,2018-02-04T14:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1404625,https://www.tvmaze.com/episodes/1404625/cbs-ne...,Episode 5,2018,5.0,regular,2018-02-04,09:00,2018-02-04T14:00:00+00:00,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1407145,https://www.tvmaze.com/episodes/1407145/xtreme...,The Scout Gets an LS!,2018,2.0,regular,2018-02-04,09:00,2018-02-04T14:00:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3110358,https://www.tvmaze.com/episodes/3110358/state-...,"Sunday, February 4, 2018, 9AM",2018,5.0,regular,2018-02-04,09:00,2018-02-04T14:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1658667,https://www.tvmaze.com/episodes/1658667/engine...,Factory Five Hot Rod Truck,2018,2.0,regular,2018-02-04,09:30,2018-02-04T14:30:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1691935,https://www.tvmaze.com/episodes/1691935/bunnic...,Beach Blanket Bunn,2,27.0,regular,2018-02-04,09:30,2018-02-04T14:30:00+00:00,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1393172,https://www.tvmaze.com/episodes/1393172/close-...,Actresses,3,10.0,regular,2018-02-04,10:00,2018-02-04T15:00:00+00:00,60,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1413266,https://www.tvmaze.com/episodes/1413266/fareed...,Episode 5,2018,5.0,regular,2018-02-04,10:00,2018-02-04T15:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1463687,https://www.tvmaze.com/episodes/1463687/am-joy...,Episode 10,2018,10.0,regular,2018-02-04,10:00,2018-02-04T15:00:00+00:00,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1404178,https://www.tvmaze.com/episodes/1404178/face-t...,2/4: Face the Nation,2018,5.0,regular,2018-02-04,10:30,2018-02-04T15:30:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1378074,https://www.tvmaze.com/episodes/1378074/giada-...,Pizza and Pasta Party,3,5.0,regular,2018-02-04,11:00,2018-02-04T16:00:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1400843,https://www.tvmaze.com/episodes/1400843/the-du...,Pro Football Experience & Combined Sports,2,19.0,regular,2018-02-04,13:00,2018-02-04T18:00:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1384343,https://www.tvmaze.com/episodes/1384343/the-du...,Dudes of Destruction & Camping,2,20.0,regular,2018-02-04,13:30,2018-02-04T18:30:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2443736,https://www.tvmaze.com/episodes/2443736/puppy-...,Puppy Bowl XIV,2018,1.0,regular,2018-02-04,15:00,2018-02-04T20:00:00+00:00,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1384047,https://www.tvmaze.com/episodes/1384047/naked-...,Naked News Magazine 2018-02-04,2018,29.0,regular,2018-02-04,17:00,2018-02-04T22:00:00+00:00,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1524948,https://www.tvmaze.com/episodes/1524948/this-w...,We're All Out of Kidneys,2018,5.0,regular,2018-02-04,17:15,2018-02-04T22:15:00+00:00,120,...,NaN,NaN,NaN,102.0,Twit,United States,US,America/New_York,NaN,NaN
22,1397728,https://www.tvmaze.com/episodes/1397728/abc-wo...,Episode 35,2018,35.0,regular,2018-02-04,18:30,2018-02-04T23:30:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1405375,https://www.tvmaze.com/episodes/1405375/super-...,Super Bowl LII - New England Patriots vs. Phil...,2018,1.0,regular,2018-02-04,18:30,2018-02-04T23:30:00+00:00,210,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1539991,https://www.tvmaze.com/episodes/1539991/nbc-ni...,Feb 4 Sun,2018,35.0,regular,2018-02-04,18:30,2018-02-04T23:30:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1421688,https://www.tvmaze.com/episodes/1421688/60-min...,60 Minutes Presents: On the 60 Minutes Menu,50,19.0,regular,2018-02-04,19:00,2018-02-05T00:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2623094,https://www.tvmaze.com/episodes/2623094/washin...,Fingerling Potatoes,5,6.0,regular,2018-02-04,19:00,2018-02-05T00:00:00+00:00,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,3488706,https://www.tvmaze.com/episodes/3488706/kasie-...,Episode 5,2018,5.0,regular,2018-02-04,19:00,2018-02-05T00:00:00+00:00,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1371168,https://www.tvmaze.com/episodes/1371168/counte...,The Lost Art of Diplomacy,1,3.0,regular,2018-02-04,20:00,2018-02-05T01:00:00+00:00,60,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1398010,https://www.tvmaze.com/episodes/1398010/alaska...,The Blind Side,7,NaN,insignificant_special,2018-02-04,20:00,2018-02-05T01:00:00+00:00,180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1402640,https://www.tvmaze.com/episodes/1402640/meow-m...,Nobody's Purr-fect,1,12.0,regular,2018-02-04,20:00,2018-02-05T01:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2193435,https://www.tvmaze.com/episodes/2193435/master...,Comida saludable para niños,1,4.0,regular,2018-02-04,20:00,2018-02-05T01:00:00+00:00,60,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1378070,https://www.tvmaze.com/episodes/1378070/worst-...,Leftovers Again?,12,5.0,regular,2018-02-04,21:00,2018-02-05T02:00:00+00:00,60,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1364750,https://www.tvmaze.com/episodes/1364750/divorc...,Ohio,2,4.0,regular,2018-02-04,22:00,2018-02-05T03:00:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1377970,https://www.tvmaze.com/episodes/1377970/food-f...,Crime Biters,3,15.0,regular,2018-02-04,22:00,2018-02-05T03:00:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1390505,https://www.tvmaze.com/episodes/1390505/seekin...,13 is Enough!,1,4.0,regular,2018-02-04,22:00,2018-02-05T03:00:00+00:00,60,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1384390,https://www.tvmaze.com/episodes/1384390/this-i...,Super Bowl Sunday,2,14.0,regular,2018-02-04,22:15,2018-02-05T03:15:00+00:00,80,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1376665,https://www.tvmaze.com/episodes/1376665/crashi...,Porter Got HBO,2,4.0,regular,2018-02-04,22:30,2018-02-05T03:30:00+00:00,30,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1392694,https://www.tvmaze.com/episodes/1392694/starta...,Frank Oz and the Science of Puppeteering,4,17.0,regular,2018-02-04,23:00,2018-02-05T04:00:00+00:00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,1379986,https://www.tvmaze.com/episodes/1379986/robot-...,"3 2 1 2 333, 222, 3...66?",9,7.0,regular,2018-02-04,23:30,2018-02-05T04:30:00+00:00,15,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,1387162,https://www.tvmaze.com/episodes/1387162/hot-st...,The Bractegon,1,7.0,regular,2018-02-04,00:00,2018-02-05T05:00:00+00:00,15,...,https://static.tvmaze.com/uploads/images/mediu...,https://static.tvmaze.com/uploads/images/origi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df_schedule.sort_values("runtime", ascending=False)[["show.name","runtime","airtime"]].head(3)

                    show.name  runtime airtime
23                 Super Bowl      210   18:30
29  Alaska: The Last Frontier      180   20:00
21          This Week in Tech      120   17:15

2\. Among all shows that aired in the U.S. on Feburary 4, 2018, which non-voice actors appeared on more than one show? Note: some people are credited with multiple rows on the same show and thus appear as multiple rows in the data frame.

Hint: You will need to write a for loop to make multiple requests. Use the "show.id" from the data from part 1, and use the ["Shows" endpoint](http://www.tvmaze.com/api#show-cast) to get the cast of each show. Don't forget to stagger your requests, or you will be blocked by the website!

In [75]:
# YOUR CODE HERE. ADD CELLS AS NEEDED

show_ids = df_schedule["show.id"].unique()
len(show_ids)

38

In [76]:
## https://api.tvmaze.com/shows/1/cast
import time

cast_records = []

for show_id in show_ids:
    response = requests.get(f"https://api.tvmaze.com/shows/{show_id}/cast")
    if response.status_code != 200:
        print("Skipped", show_id, "state error", response.status_code)
        continue
    members = response.json()
    for member in members:
        member["show_id"] = int(show_id)
    cast_records.extend(members)
    time.sleep(0.5)

# Tasty API

[Tasty.co](http://tasty.co) is a website and app that offers food recipes. They have made these recipes available through a [a REST API](https://rapidapi.com/apidojo/api/tasty). However, unlike the TVMaze API, this one requires authentication.

Specifically, you will need to create an account and subscribe to the "Basic" (free) plant. You will then be provided with an API key (X-Rapid-API-Key) that will need to be supplied with every request you make. This is used to track and limit usage.

1. [create an account](https://rapidapi.com/apidojo/api/tasty) and subscribe to the "Basic" (free) plan
2. log in and copy the X-RapidAPI-Key, which is a long string of letters and digits
3. paste this key to replace "PUT-YOUR-KEY-HERE" in the `headers` below

If you did everything correctly, then running the cell below should return a JSON object containing all the tags recognized by the Tasty API.

In [78]:
import requests

domain = "https://tasty.p.rapidapi.com"
endpoint = "tags/list"
url = f"{domain}/{endpoint}"

# TODO: Update the `headers` with your X-RapidAPI-Key.
headers = {
	"X-RapidAPI-Key": "2ac50b7414msh1b96808fa566680p1da2e4jsn694e5e868401",
	"X-RapidAPI-Host": "tasty.p.rapidapi.com"
}

# Make an HTTP request to the REST API, get the JSON response.
response = requests.get(url, headers=headers)
response.json()

{'count': 588,
 'results': [{'root_tag_type': 'cuisine',
   'name': 'brazilian',
   'id': 64446,
   'parent_tag_name': 'central_south_american',
   'display_name': 'Brazilian',
   'type': 'central_south_american'},
  {'root_tag_type': 'cuisine',
   'name': 'german',
   'id': 64450,
   'parent_tag_name': 'european',
   'display_name': 'German',
   'type': 'european'},
  {'root_tag_type': 'healthy',
   'name': 'healthy',
   'id': 64466,
   'parent_tag_name': None,
   'display_name': 'Healthy',
   'type': 'healthy'},
  {'root_tag_type': 'dietary',
   'name': 'vegetarian',
   'id': 64469,
   'parent_tag_name': 'dietary',
   'display_name': 'Vegetarian',
   'type': 'dietary'},
  {'root_tag_type': 'seasonal',
   'name': 'christmas',
   'id': 64473,
   'parent_tag_name': 'holidays',
   'display_name': 'Christmas',
   'type': 'holidays'},
  {'root_tag_type': 'seasonal',
   'name': 'halloween',
   'id': 64476,
   'parent_tag_name': 'holidays',
   'display_name': 'Halloween',
   'type': 'holidays'},
  {'root_tag_type': 'meal',
   'name': 'breakfast',
   'id': 64483,
   'parent_tag_name': 'meal',
   'display_name': 'Breakfast',
   'type': 'meal'},
  {'root_tag_type': 'meal',
   'name': 'drinks',
   'id': 64487,
   'parent_tag_name': 'meal',
   'display_name': 'Drinks',
   'type': 'meal'},
  {'root_tag_type': 'appliance',
   'name': 'baking',
   'id': 64492,
   'parent_tag_name': 'appliance',
   'display_name': 'Baking',
   'type': 'appliance'},
  {'root_tag_type': 'cooking_style',
   'name': 'grill',
   'id': 64494,
   'parent_tag_name': 'cooking_style',
   'display_name': 'Grill',
   'type': 'cooking_style'},
  {'root_tag_type': 'seasonal',
   'name': 'game_day',
   'id': 64501,
   'parent_tag_name': 'occasion',
   'display_name': 'Game Day',
   'type': 'occasion'},
  {'root_tag_type': 'meal',
   'name': 'weeknight',
   'id': 64505,
   'parent_tag_name': 'dinner',
   'display_name': 'Weeknight',
   'type': 'dinner'},
  {'root_tag_type': 'seasonal',
   'name': 'spring',
   'id': 64509,
   'parent_tag_name': 'seasonal',
   'display_name': 'Spring',
   'type': 'seasonal'},
  {'root_tag_type': 'cooking_style',
   'name': 'one_pot_or_pan',
   'id': 65855,
   'parent_tag_name': 'cooking_style',
   'display_name': 'One-Pot or Pan',
   'type': 'cooking_style'},
  {'root_tag_type': 'cooking_style',
   'name': 'stuffed',
   'id': 65856,
   'parent_tag_name': None,
   'display_name': 'Stuffed',
   'type': 'cooking_style'},
  {'root_tag_type': 'equipment',
   'name': 'colander',
   'id': 1247770,
   'parent_tag_name': None,
   'display_name': 'Colander',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'ice_cream_scoop',
   'id': 1247772,
   'parent_tag_name': None,
   'display_name': 'Ice Cream Scoop',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'oven_mitts',
   'id': 1247775,
   'parent_tag_name': None,
   'display_name': 'Oven Mitts',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'plastic_wrap',
   'id': 1247784,
   'parent_tag_name': None,
   'display_name': 'Plastic Wrap',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'spatula',
   'id': 1247788,
   'parent_tag_name': None,
   'display_name': 'Spatula',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'tongs',
   'id': 1247790,
   'parent_tag_name': None,
   'display_name': 'Tongs',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'whisk',
   'id': 1247793,
   'parent_tag_name': None,
   'display_name': 'Whisk',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'baking_pan',
   'id': 1280500,
   'parent_tag_name': None,
   'display_name': 'Baking Pan',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'dry_measuring_cups',
   'id': 1280507,
   'parent_tag_name': None,
   'display_name': 'Dry Measuring Cups',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'measuring_spoons',
   'id': 1280508,
   'parent_tag_name': None,
   'display_name': 'Measuring Spoons',
   'type': 'equipment'},
  {'root_tag_type': 'equipment',
   'name': 'mixing_bowl',
   'id': 1280510,
   'parent_tag_name': None,
   'display_name': 'Mixing Bowl',
   'type': 'equipment'},
  {'root_tag_type': 'business_tags',
   'name': 'one_top_friendly',
   'id': 1691103,
   'parent_tag_name': None,
   'display_name': 'One Top Friendly',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'one_top_app_dessert',
   'id': 2651758,
   'parent_tag_name': None,
   'display_name': 'Dessert',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'one_top_app_grains',
   'id': 2651759,
   'parent_tag_name': None,
   'display_name': 'Grains',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'one_top_app_sauces',
   'id': 2651760,
   'parent_tag_name': None,
   'display_name': 'Sauces',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'one_top_app_steak',
   'id': 2651761,
   'parent_tag_name': None,
   'display_name': 'Steak',
   'type': 'business_tags'},
  {'root_tag_type': 'dietary',
   'name': 'pescatarian',
   'id': 3801552,
   'parent_tag_name': 'dietary',
   'display_name': 'Pescatarian',
   'type': 'dietary'},
  {'root_tag_type': 'feature_page',
   'name': 'qfp_baking',
   'id': 5812431,
   'parent_tag_name': None,
   'display_name': 'Quarantine Cooking: Baking',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'tasty_ewd_fifteen',
   'id': 6117479,
   'parent_tag_name': None,
   'display_name': 'Tasty EWD Fifteen',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'tasty_ewd_tips',
   'id': 6117480,
   'parent_tag_name': None,
   'display_name': 'Tasty EWD Tips',
   'type': 'feature_page'},
  {'root_tag_type': 'business_tags',
   'name': 'every_occasion',
   'id': 6143339,
   'parent_tag_name': None,
   'display_name': 'Every Occasion',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'holiday_treats',
   'id': 6337137,
   'parent_tag_name': None,
   'display_name': 'Holiday Treats',
   'type': 'business_tags'},
  {'root_tag_type': 'business_tags',
   'name': 'lil_brut',
   'id': 6361775,
   'parent_tag_name': None,
   'display_name': 'Lil Brut',
   'type': 'business_tags'},
  {'root_tag_type': 'feature_page',
   'name': 'tasty_holiday_festive_favorites',
   'id': 6389775,
   'parent_tag_name': None,
   'display_name': 'Tasty Holiday: Festive Favorites',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'nynm_expert',
   'id': 6543462,
   'parent_tag_name': None,
   'display_name': 'NYNM Expert',
   'type': 'feature_page'},
  {'root_tag_type': 'seasonal',
   'name': 'lunar_new_year',
   'id': 6573766,
   'parent_tag_name': 'holidays',
   'display_name': 'Lunar New Year',
   'type': 'holidays'},
  {'root_tag_type': 'feature_page',
   'name': 'mc_breakfast_sweet',
   'id': 6683350,
   'parent_tag_name': None,
   'display_name': 'MC Breakfast Sweet',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'mc_breakfast_easy',
   'id': 6683353,
   'parent_tag_name': None,
   'display_name': 'MC Breakfast Easy',
   'type': 'feature_page'},
  {'root_tag_type': 'seasonal',
   'name': 'st_patrick_s_day',
   'id': 6711300,
   'parent_tag_name': 'holidays',
   'display_name': "St. Patrick's Day",
   'type': 'holidays'},
  {'root_tag_type': 'feature_page',
   'name': 'spring_eat',
   'id': 6718869,
   'parent_tag_name': None,
   'display_name': 'Spring Eat',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'spring_drink',
   'id': 6718870,
   'parent_tag_name': None,
   'display_name': 'Spring Drink',
   'type': 'feature_page'},
  {'root_tag_type': 'seasonal',
   'name': 'passover',
   'id': 6742797,
   'parent_tag_name': 'holidays',
   'display_name': 'Passover',
   'type': 'holidays'},
  {'root_tag_type': 'feature_page',
   'name': 'budget_10',
   'id': 6830248,
   'parent_tag_name': None,
   'display_name': 'Budget 10',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'budget_shop',
   'id': 6830251,
   'parent_tag_name': None,
   'display_name': 'Budget Shop',
   'type': 'feature_page'},
  {'root_tag_type': 'cuisine',
   'name': 'west_african',
   'id': 6953016,
   'parent_tag_name': 'african',
   'display_name': 'West African',
   'type': 'african'},
  {'root_tag_type': 'feature_page',
   'name': 'mccormick_ugc_one_pot_winners',
   'id': 6986104,
   'parent_tag_name': None,
   'display_name': 'McCormick UGC One Pot Winners',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'summer_eat',
   'id': 7041320,
   'parent_tag_name': None,
   'display_name': 'Summer Eat',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'uber_game_day_ribs',
   'id': 7436546,
   'parent_tag_name': None,
   'display_name': 'Uber Game Day Ribs',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'thanksgiving_desserts',
   'id': 7510771,
   'parent_tag_name': None,
   'display_name': 'Thanksgiving Desserts',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'thanksgiving_slow',
   'id': 7510780,
   'parent_tag_name': None,
   'display_name': 'Thanksgiving Slow',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'shoppable_recipes_thanksgiving',
   'id': 7559499,
   'parent_tag_name': None,
   'display_name': 'Shoppable Recipes Thanksgiving',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'shoppable_recipes_holiday_dinners',
   'id': 7559500,
   'parent_tag_name': None,
   'display_name': 'Shoppable Recipes Holiday Dinners',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'live_jasmine_and_tucker',
   'id': 7560081,
   'parent_tag_name': None,
   'display_name': 'Live Jasmine and Tucker',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'franks_dips',
   'id': 7723150,
   'parent_tag_name': None,
   'display_name': 'Franks Dips',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'butterfinger_runner_up_bark',
   'id': 7783333,
   'parent_tag_name': None,
   'display_name': 'Butterfinger Runner Up Bark',
   'type': 'feature_page'},
  {'root_tag_type': 'healthy',
   'name': 'low_calorie',
   'id': 8091916,
   'parent_tag_name': 'healthy',
   'display_name': 'Low-Calorie',
   'type': 'healthy'},
  {'root_tag_type': 'healthy',
   'name': 'low_sugar',
   'id': 8091918,
   'parent_tag_name': 'healthy',
   'display_name': 'Low-Sugar',
   'type': 'healthy'},
  {'root_tag_type': 'healthy',
   'name': 'low_fat',
   'id': 8091919,
   'parent_tag_name': 'healthy',
   'display_name': 'Low-Fat',
   'type': 'healthy'},
  {'root_tag_type': 'feature_page',
   'name': 'mccormick_world_desserts',
   'id': 8104113,
   'parent_tag_name': None,
   'display_name': 'McCormick World Desserts',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'homemade_holiday',
   'id': 8747851,
   'parent_tag_name': None,
   'display_name': 'Homemade Holiday',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'nigeria_african_cuisine',
   'id': 8874992,
   'parent_tag_name': None,
   'display_name': 'Nigeria African Cuisine',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'trinidad_african_cuisine',
   'id': 8875007,
   'parent_tag_name': None,
   'display_name': 'Trinidad African Cuisine',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'cuba_african_cuisine',
   'id': 8875008,
   'parent_tag_name': None,
   'display_name': 'Cuba African Cuisine',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'incredible_egg_lunches',
   'id': 8907402,
   'parent_tag_name': None,
   'display_name': 'Incredible Egg Lunches',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'country_crock_desserts',
   'id': 9104326,
   'parent_tag_name': None,
   'display_name': 'Country Crock Desserts',
   'type': 'feature_page'},
  {'root_tag_type': 'cuisine',
   'name': 'asian',
   'id': 9295873,
   'parent_tag_name': 'cuisine',
   'display_name': 'Asian',
   'type': 'cuisine'},
  {'root_tag_type': 'seasonal',
   'name': 'new_years',
   'id': 9299361,
   'parent_tag_name': 'holidays',
   'display_name': 'New Years',
   'type': 'holidays'},
  {'root_tag_type': 'meal',
   'name': 'beverages',
   'id': 9299370,
   'parent_tag_name': 'breakfast',
   'display_name': 'Beverages',
   'type': 'breakfast'},
  {'root_tag_type': 'meal',
   'name': 'coffee',
   'id': 9299372,
   'parent_tag_name': 'drinks',
   'display_name': 'Coffee',
   'type': 'drinks'},
  {'root_tag_type': 'meal',
   'name': 'waffles',
   'id': 9299396,
   'parent_tag_name': 'sweet_breakfasts',
   'display_name': 'Waffles',
   'type': 'sweet_breakfasts'},
  {'root_tag_type': 'meal',
   'name': 'salads',
   'id': 9299495,
   'parent_tag_name': 'lunch',
   'display_name': 'Salads',
   'type': 'lunch'},
  {'root_tag_type': 'meal',
   'name': 'casseroles',
   'id': 9299517,
   'parent_tag_name': 'dinner',
   'display_name': 'Casseroles',
   'type': 'dinner'},
  {'root_tag_type': 'meal',
   'name': 'chilis',
   'id': 9299518,
   'parent_tag_name': 'dinner',
   'display_name': 'Chilis',
   'type': 'dinner'},
  {'root_tag_type': 'meal',
   'name': 'pot_roast',
   'id': 9299524,
   'parent_tag_name': 'dinner',
   'display_name': 'Pot Roast',
   'type': 'dinner'},
  {'root_tag_type': 'meal',
   'name': 'quiches',
   'id': 9299525,
   'parent_tag_name': 'dinner',
   'display_name': 'Quiches',
   'type': 'dinner'},
  {'root_tag_type': 'meal',
   'name': 'tacos_burritos',
   'id': 9299529,
   'parent_tag_name': 'dinner',
   'display_name': 'Tacos & Burritos',
   'type': 'dinner'},
  {'root_tag_type': 'meal',
   'name': 'cakes',
   'id': 9299665,
   'parent_tag_name': 'desserts',
   'display_name': 'Cakes',
   'type': 'desserts'},
  {'root_tag_type': 'feature_page',
   'name': 'kings_hawaiian_sliders',
   'id': 9345544,
   'parent_tag_name': None,
   'display_name': 'Kings Hawaiian Sliders',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'kings_hawaiian_bbq_dessert',
   'id': 9345547,
   'parent_tag_name': None,
   'display_name': 'Kings Hawaiian BBQ Dessert',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'kings_hawaiian_pizza',
   'id': 10032069,
   'parent_tag_name': None,
   'display_name': 'Kings Hawaiian Pizza',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'kings_hawaiian_vegetarian',
   'id': 10032070,
   'parent_tag_name': None,
   'display_name': 'Kings Hawaiian Vegetarian',
   'type': 'feature_page'},
  {'root_tag_type': 'business_tags',
   'name': 'ghoulishly_good_desserts',
   'id': 10080870,
   'parent_tag_name': None,
   'display_name': 'ghoulishly_good_desserts',
   'type': 'business_tags'},
  {'root_tag_type': 'feature_page',
   'name': 'jammy_cookies',
   'id': 10296618,
   'parent_tag_name': None,
   'display_name': 'Jammy Cookies',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'chewy_cookies',
   'id': 10296621,
   'parent_tag_name': None,
   'display_name': 'Chewy Cookies',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'one_dish_wonders',
   'id': 10315443,
   'parent_tag_name': None,
   'display_name': 'One Dish Wonders',
   'type': 'feature_page'},
  {'root_tag_type': 'ingredients_to_avoid',
   'name': 'seafood',
   'id': 10623610,
   'parent_tag_name': 'ingredients_to_avoid',
   'display_name': 'Seafood',
   'type': 'ingredients_to_avoid'},
  {'root_tag_type': 'ingredients_to_avoid',
   'name': 'chicken',
   'id': 10623612,
   'parent_tag_name': 'ingredients_to_avoid',
   'display_name': 'Chicken',
   'type': 'ingredients_to_avoid'},
  {'root_tag_type': 'ingredients_to_avoid',
   'name': 'peanuts',
   'id': 10640007,
   'parent_tag_name': 'ingredients_to_avoid',
   'display_name': 'Peanuts',
   'type': 'ingredients_to_avoid'},
  {'root_tag_type': 'dietary',
   'name': 'halal',
   'id': 10742774,
   'parent_tag_name': 'dietary',
   'display_name': 'Halal',
   'type': 'dietary'},
  {'root_tag_type': 'feature_page',
   'name': 'mccormick_more_inspiration',
   'id': 10956868,
   'parent_tag_name': None,
   'display_name': 'McCormick More Inspiration',
   'type': 'feature_page'},
  {'root_tag_type': 'business_tags',
   'name': 'thomas_meal_planning_3',
   'id': 11002783,
   'parent_tag_name': None,
   'display_name': 'Thomas Meal Planning 3',
   'type': 'business_tags'},
  {'root_tag_type': 'feature_page',
   'name': 'cap_one_starters',
   'id': 11173648,
   'parent_tag_name': None,
   'display_name': 'Cap One Starters',
   'type': 'feature_page'},
  {'root_tag_type': 'meal',
   'name': 'sandwiches_for_every_taste',
   'id': 11196928,
   'parent_tag_name': 'lunch',
   'display_name': 'Sandwiches For Every Taste',
   'type': 'lunch'},
  {'root_tag_type': 'feature_page',
   'name': 'joelle',
   'id': 11230777,
   'parent_tag_name': None,
   'display_name': 'Joelle',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'comfort_reset_breakfasts',
   'id': 13968395,
   'parent_tag_name': None,
   'display_name': 'Comfort Reset: Breakfasts',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'mvp_mains',
   'id': 14252708,
   'parent_tag_name': None,
   'display_name': 'MVP: Mains',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'mvp_sweets',
   'id': 14252710,
   'parent_tag_name': None,
   'display_name': 'MVP: Sweets',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': '15_minute_recipes_uk',
   'id': 14388516,
   'parent_tag_name': None,
   'display_name': '15 Minute Recipes UK',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'coke_burgers',
   'id': 14431336,
   'parent_tag_name': None,
   'display_name': 'Coke Burgers',
   'type': 'feature_page'},
  {'root_tag_type': 'feature_page',
   'name': 'tasty_reads_uk',
   'id': 14875708,
   'parent_tag_name': None,
   'display_name': 'Tasty Reads UK',
   'type': 'feature_page'},
  {'root_tag_type': 'cuisine',
   'name': 'chinese',
   'id': 64448,
   'parent_tag_name': 'asian',
   'display_name': 'Chinese',
   'type': 'asian'},
  {'root_tag_type': 'cuisine',
   'name': 'french',
   'id': 64449,
   'parent_tag_name': 'european',
   'display_name': 'French',
   'type': 'european'},
  {'root_tag_type': 'cuisine',
   'name': 'japanese',
   'id': 64454,
   'parent_tag_name': 'asian',
   'display_name': 'Japanese',
   'type': 'asian'},
  {'root_tag_type': 'healthy',
   'name': 'low_carb',
   'id': 64467,
   'parent_tag_name': 'healthy',
   'display_name': 'Low-Carb',
   'type': 'healthy'},
  {'root_tag_type': 'seasonal',
   'name': 'valentines_day',
   'id': 64480,
   'parent_tag_name': 'holidays',
   'display_name': "Valentine's Day",
   'type': 'holidays'},
  {'root_tag_type': 'meal',
   'name': 'dinner',
   'id': 64486,
   'parent_tag_name': 'meal',
   'display_name': 'Dinner',
   'type': 'meal'},
  {'root_tag_type': 'cooking_style',
   'name': 'steam',
   'id': 64498,
   'parent_tag_name': 'cooking_style',
   'display_name': 'Steam',
   'type': 'cooking_style'},
  {'root_tag_type': 'occasion',
   'name': 'happy_hour',
   'id': 64502,
   'parent_tag_name': None,
   'display_name': 'Happy Hour',
   'type': 'occasion'},
  {'root_tag_type': 'seasonal',
   'name': 'party',
   'id': 64503,
   'parent_tag_name': 'occasion',
   'display_name': 'Party',
   'type': 'occasion'},
  {'root_tag_type': 'business_tags',
   'name': 'tasty_cookbook',
   'id': 64506,
   'parent_tag_name': None,
   'display_name': 'Tasty Cookbook',
   'type': 'business_tags'},
  {'root_tag_type': 'seasonal',
   'name': 'fall',
   'id': 64508,

You will need to pass these `headers` with every HTTP request to the API. The API key (X-RapidAPI-Key) is how the server keeps track of how many requests you have made.

Take a look at [the documentation](https://rapidapi.com/apidojo/api/tasty). We will use the recipes/list endpoint.

Make sure you are logged into the account you are created, and select the recipes/list endpoint from the menu at left. Notice that this brings up a form that you can fill in, which generates the corresponding code.  By default, it provides Node.js code; change this to Python with the Requests client.

1\. Search for recipes containing "daikon" (an Asian radish) and request the JSON data, and convert it to a Pandas data frame.

In [79]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
endpoint = "recipes/list"
url = f"{domain}/{endpoint}"

params = {
    "from": 0,
    "size": 40,
    "q": "daikon"
}

In [80]:
response = requests.get(
    url,
    headers=headers,
    params=params
)

print(response.status_code)

200

In [81]:
data_daikon = response.json()

data_daikon.keys()

dict_keys(['count', 'results', 'aggregations'])

In [82]:
df_daikon = pd.json_normalize(data_daikon["results"])

df_daikon.head()

,nutrition_visibility,country,instructions,keywords,facebook_posts,language,seo_path,id,brand,slug,...,total_time_tier.tier,total_time_tier.display_tier,total_time_tier,tips_summary.by_line,tips_summary.header,tips_summary.content,brand.image_url,brand.name,brand.id,brand.slug
0,auto,US,"[{'start_time': 9666, 'appliance': None, 'end_...",None,[],eng,"8757513,9295873,64461",4490,NaN,top-chef-junior-pork-banh-mi-burger,...,under_30_minutes,Under 30 minutes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,auto,US,"[{'start_time': 7666, 'appliance': None, 'end_...","beef bulgogi, creamy and crunchy foods, easy b...",[],eng,"8757513,9295873,64455",6046,NaN,instant-pot-beef-bulgogi,...,NaN,NaN,NaN,Powered By Botatouille,Highlights,• Experiment with different variations to make...,NaN,NaN,NaN,NaN
2,auto,US,"[{'start_time': 1000, 'appliance': None, 'end_...",,[],eng,"8757513,9295873,64461",5643,NaN,banh-mi-meatball-sandwich,...,under_2_hours,Under 2 hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,auto,US,"[{'start_time': 0, 'appliance': None, 'end_tim...","chicken banh mi, do chua recipe, easy weeknigh...",[],eng,"8757513,9295873,64461",9820,NaN,grilled-chicken-banh-mi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,auto,US,"[{'start_time': 5833, 'appliance': None, 'hack...","tasty, tasty_vegetarian",[],eng,"8757513,9295873,64455",4258,NaN,how-to-make-kimchi,...,under_2.5_hours,Under 2.5 hours,NaN,Powered By Botatouille,Highlights,• Substitute gochugaru with paprika or a mix o...,NaN,NaN,NaN,NaN

2\. How many recipes containing daikon are there? Which one is the cheapest per portion?

In [83]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
data_daikon["count"]

16

In [84]:
df_daikon[["name", "price.portion"]]

                                                 name  price.portion
0                 Top Chef Junior Pork Bánh Mì Burger          650.0
1                            Instant Pot Beef Bulgogi         1050.0
2                           Banh Mi Meatball Sandwich          700.0
3                                     Chicken Bánh Mì          800.0
4                            How To Make Vegan Kimchi          650.0
5                                   Japanese Omelette         1450.0
6                                   Low-Carb Pad Thai          500.0
7                                   Fried Carrot Cake          850.0
8                        Bibimbap By Chef Esther Choi         1350.0
9                     Grilled Lemongrass Pork Bánh Mì          850.0
10        Vegan Tofu Bao Buns With Pickled Vegetables          300.0
11                              How To Make Vegan Pho          900.0
12  Bun Bo Xa Ot (Vietnamese Steak And Rice Noodle...         1250.0
13  Golden Chicken Sandwich As Made By Chef Kuniko...         2200.0
14                                  Burnt End Bánh Mì         1000.0
15     Instant Pot Miso Butter Salmon And Ginger Rice         2850.0

In [85]:
df_daikon[
    ["name", "price.portion"]
].sort_values("price.portion").head(1)

                                           name  price.portion
10  Vegan Tofu Bao Buns With Pickled Vegetables          300.0

3\. Find recipes containing avocado and request the JSON data.

**Hint:** Note that there are hundreds of results, but the API only returns 20 results by default and only 40 results maximum, even if you specify the `size=` parameter, so you will need to use a `for` loop, incrementing the `from=` parameter. Be sure to respect the API's rate limits (or you may be blocked!)

**Note:** Recall from the example in the reading that we created an empty list `episodes = []` and then added the results of each request to it in the for loop with `episodes.extend(response.json())`. But note that in the recipes/list endpoint there are two keys: count and results. We only want the results so try instead `.extend(response.json()).get("results")`.

**Suggestion:** Try writing a loop that only makes 2 or 3 requests first so you can test that it's working correctly. Also, make sure you use separate cells for code that makes requests to the API versus processing of the results; you don't want to rerun the requests unless absolutely necessary!

In [87]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
import time

params = {
    "from": 0,
    "size": 40,
    "q": "avocado"
}

response = requests.get(url, headers=headers, params=params)
avocado_data = response.json()

total_recipes = avocado_data["count"]
avocado_recipes = avocado_data["results"]

print("Total available:", total_recipes)
print("Downloaded:", len(avocado_recipes))

Total available: 444
Downloaded: 40

In [88]:
for start in range(40, total_recipes, 40):
    params = {
        "from": start,
        "size": 40,
        "q": "avocado"
    }

    response = requests.get(url, headers=headers, params=params)
    
    if response.status_code != 200:
        print("Request failed at:", start)
        break

    page_data = response.json()
    avocado_recipes.extend(page_data["results"])

    print("Downloaded:", len(avocado_recipes))
    time.sleep(1)

Downloaded: 80
Downloaded: 120
Downloaded: 160
Downloaded: 200
Downloaded: 240
Downloaded: 280
Downloaded: 320
Downloaded: 360
Downloaded: 400
Downloaded: 440
Downloaded: 444

In [89]:
df_avocado = pd.json_normalize(avocado_recipes)

df_avocado.shape

(444, 77)

In [90]:
print("Expected:", total_recipes)
print("Downloaded:", len(df_avocado))

Expected: 444
Downloaded: 444

4\. For the recipes containing avocado, compute the proportion of reviews that are positive. For the avocado recipes with over 500 reviews, which one has the highest proportion of positive reviews?

In [91]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
df_avocado["total_reviews"] = (
    df_avocado["user_ratings.count_positive"] +
    df_avocado["user_ratings.count_negative"]
)

In [92]:
df_avocado["positive_proportion"] = (
    df_avocado["user_ratings.count_positive"] /
    df_avocado["total_reviews"]
)

In [93]:
popular_avocado = df_avocado[
    df_avocado["total_reviews"] > 500
]

In [94]:
popular_avocado[
    [
        "name",
        "user_ratings.count_positive",
        "user_ratings.count_negative",
        "total_reviews",
        "positive_proportion"
    ]
].sort_values(
    "positive_proportion",
    ascending=False
).head(1)

,name,user_ratings.count_positive,user_ratings.count_negative,total_reviews,positive_proportion
13,Grilled Salmon With Avocado Salsa,1874.0,24.0,1898.0,0.987355

5\. Take the avocado JSON data from above (you do NOT need to read in the data from the REST API again). How many recipes are vegetarian? You should be able to identify this from the "tags" attribute.

Hint: Try using `json_normalize` with "tags" as the record path to flatten the data so that there is one row for each tag.

In [95]:
# YOUR CODE HERE. ADD CELLS AS NEEDED
df_tags = pd.json_normalize(
    avocado_recipes,
    record_path="tags",
    meta=["id", "name"],
    meta_prefix="recipe."
)

df_tags.head()

,root_tag_type,name,id,parent_tag_name,display_name,type,recipe.id,recipe.name
0,cuisine,north_american,64444,cuisine,North American,cuisine,56,Avocado Carbonara
1,cuisine,italian,64453,european,Italian,european,56,Avocado Carbonara
2,cooking_style,comfort_food,64462,cooking_style,Comfort Food,cooking_style,56,Avocado Carbonara
3,healthy,healthy,64466,None,Healthy,healthy,56,Avocado Carbonara
4,difficulty,easy,64471,difficulty,Easy,difficulty,56,Avocado Carbonara

In [96]:
vegetarian_recipes = df_tags[
    df_tags["name"] == "vegetarian"
]

In [97]:
vegetarian_recipes["recipe.id"].nunique()

207

In [98]:
vegetarian_recipes[
    ["recipe.id", "recipe.name"]
].drop_duplicates()

      recipe.id                          recipe.name
72         3932           Avocado Quinoa Power Salad
143        3363                        Avocado Toast
167         232  Cucumber, Tomato, And Avocado Salad
315         654                        Avocado Salsa
332        2875         Egg, Avocado, & Tomato Toast
...         ...                                  ...
11561      6460             Vegetable Quinoa Biryani
11582      6625         Sheet Pan Sweet Potato Tacos
11652      7096   Easy Vegan Asian Tofu Nourish Bowl
11676      6455            Fusion Chana Masala Tacos
11702      6487                Instant Pot Pav Bhaji

[207 rows x 2 columns]